[project]
name = "dagster-ray"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.10.10",
    "dagster-webserver>=1.10.10",
    "pandas>=2.2.3",
]

[tool.dagster]
project="dagster_test"
module_name="dagster_test.definitions"
code_location_name="dagster_test"